import { getClasses } from "./components/charClasses.js";
import { getMyPic } from "./components/charImage.js";
import { getRace } from "./components/charRace.js";
import { stats } from "./components/charStats.js";
import { getSkill } from "./components/charSkills.js";
getClasses();
getRace();
stats();
getMyPic();
getSkill();
